### ISSUE TITLE
Unable to manage file: Jinja error: mysql/map.jinja

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/mysql-formula#210]
Hi!

I'm running the master branch. I get the following when applying mysql.config.  Any idea what is happening here? 

```
ID: mysql_config
    Function: file.managed
        Name: /etc/mysql/my.cnf
      Result: False
     Comment: Unable to manage file: Jinja error: mysql/map.jinja
              Traceback (most recent call last):
                File "/var/tmp/.salt_1a862b_salt/py2/salt/utils/templates.py", line 393, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/var/tmp/.salt_1a862b_salt/py2/jinja2/environment.py", line 1008, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/var/tmp/.salt_1a862b_salt/py2/jinja2/environment.py", line 780, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 7, in top-level template code
                File "/var/tmp/.salt_1a862b_salt/py2/salt/utils/jinja.py", line 140, in get_source
                  raise TemplateNotFound(template)
              TemplateNotFound: mysql/map.jinja
              
              ; line 7
              
              ---
              [...]
              # This config is generated by SALTSTACK
              # and all change will be overrided on next salt call
              {#-
              ===== FETCH DATA =====
              -#}
              {% from tpldir ~ "/map.jinja" import mysql with context %}    <======================
              {%- from tpldir ~ "/supported_sections.yaml" import supported_sections with context -%}
              {#-
              ===== COMBINE DATA =====
              -#}
              {%- set goodParamList = mysql.config.sections -%}
              [...]
              ---
     Started: 12:10:22.786369
    Duration: 30.201 ms
```

This also renders an output which seems strange to me (below). I'm not sure about the tmpdlr line. Maybe I'm just a n00b. Please help. 

```
mysql_config:
  file.managed:
    - name: /etc/mysql/my.cnf
    - template: jinja

    - source: salt://mysql/files/my.cnf

    - context:
      tpldir: mysql
    
    - user: root
    - group: root
    - mode: 644
```

**Comment by mostafahussein** [comment]
This error raised because salt cannot find the jinja file as described in here:
```
              TemplateNotFound: mysql/map.jinja
```
So what is the actual path of the `map.jinja` ?

**Comment by waynegemmell** [comment]
Sorry, N00b error. I needed to specify the file in a Saltfile. This is salt-ssh related. Thanks for replying.

**Comment by craigafinch** [comment]
A good explanation of this problem and possible solutions can be found here: https://github.com/saltstack/salt/issues/21370
